### ISSUE TITLE
Need clarification for sml example

### ISSUE THREAD

**Issue by ladislas** [Speckobst/fsm_examples#1]
Hi there! 

First of all, thanks a lot for putting together those great examples! It really helped me get started with boost::sml.

I have a question though, about something I don't quite understand, regarding this example:

https://github.com/ubeh/fsm_examples/tree/master/sml

- In `auto operator()()`, `struct FsmImpl` uses the lambdas `ac_start` and `ac_stop`, both using `IController *`. 
- `class Controller` has a private `boost::sml::sm<FsmImpl> fsm_`
- `class Controller` constructor is defined as:

``` cpp
Controller::Controller() : fsm_(static_cast<IController*>(this)) {}
```

I don't understand where the `fsm_(static_cast<IController*>(this)` part comes from?

I don't see any reference to `IController` in `FsmImpl`. Is that some magic added by `boost::sml::sm<FsmImpl>`?

Or maybe I'm missing something so obvious it will be really embarrassing.

Anyway, thanks for the help :)

**Comment by ladislas** [comment]
Alright, I think I found the answer here: https://github.com/boost-ext/sml/blob/master/example/dependencies.cpp#L48

We pass the dependencies inside the constructor.

That being said, isn't it weird that `Controller` and `FsmImpl` depend on each other?

**Comment by ubeh** [comment]
I think you have already figured it out, but the interface serves to resolve the interdependence. Controller depends on FsmImpl because it is a member. FsmImpl depends on Controller (only the interface IController) to be able to call its methods.

**Comment by ladislas** [comment]
Thanks @ubeh for the quick answer! :) 

I now have a good understand on how things work but it's still not clear to me how to use that for my embbeded project.

As an example, we have a RFID card reader and we have implemented a naive if/else/switch state machine to be able to read the cards. We have a `RFIDReaderDriver` the low level class dealing with the hardware and implementing `interface::RFIDReaderDriver`, and a `RFIDKit` that handles the different communication protocols and depends on the `interface::RFIDReaderDriver`.

The state machine would define the communication protocol, in our case ISO14443
We could have multiple state machine defining other protocols.

I'm not sure if the state machine should be inside the `RFIDKit` or outside? If it should be a member variable defined through DI? How to make those two things work together.

Maybe the protocol should have the state machines as they should not be visible. And they need to depend on `interface::RFIDReaderDriver` ?

As you can see, I'm a bit lost, the examples are always super simple and the main usually just calls `process_event` but in real life, you want to process and event base on an IRQ, user input, sensor reading, and so on.

I'm not sure all of this make sense, so please correct me if needed :)

**Comment by ubeh** [comment]
Questions about the architecture can't really be answered without detailed knowledge, but maybe my thoughts will help you a bit to find the right solution.
These examples are intentionally kept minimal and are only meant to show how to embed a state machine in a larger object while being able to call methods of that object from within the state machine. Please keep in mind the age of these examples, and that the documentation of boost::sml has grown a lot since then. There you will find more valuable examples.
To get back to your problem. The idea with interface::RFIDReaderDriver sounds good to me. It also sounds reasonable to embed state machine in RFIDKit. Here you should consider to decouple e.g. by interface. If the state machine has to call member functions of RFIDKit, the technique shown in these examples can be used - with or without interface.
I am not sure about DI. I don't see the requirement for this from your description.

**Comment by ladislas** [comment]
Thanks @ubeh for your help. I've spent more time playing with boost::sml and carefully reading the documentation. It all makes more sense now! :)
